name: Deploy AWS CDK

# Controls when the action will run.
on:
  #push:
    #branches:
      #- master
  #pull_request:
  #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: install npm
        run: 'sudo apy update -y && sudo apt install  nodejs npm -y'

      - name: install AWS CDk
        run: 'sudo npm install -g aws-cdk'

      - name: CDK Synth
        run: cdk synth
        working-directory: .

      - name: CDK Deploy
        run: cdk deploy
        working-directory: .
